eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost



microservice:
  party-service:
    endpoints:
      endpoint:
        uri: http://PARTY-SERVICE/party/create

  person-service:
    endpoints:
      endpoint:
        uri: http://PERSON-SERVICE/person/create
  account-service:
    endpoints:
      endpoint:
        uri: http://ACCOUNT-SERVICE/account/create

  customer-service:
    endpoints:
      endpoint:
        uri: http://CUSTOMER-SERVICE/customer/create
